### ISSUE TITLE
DarjeelingUtils.eventuallyActivityLaunched not working

### ISSUE THREAD

**Issue by Dambakk** [agensdev/darjeeling#1]
Trying to test if a certain activity has been launched from another activity.

Calling `DarjeelingUtils.eventuallyActivityLaunched(activity = NewActivity::class)` times out. Inlining the calls that  `eventuallyActivityLaunched` makes and managing the `Intents.*` calls in `@Before` and `@After` myself also times out.

**Comment by jaranflaath** [comment]
Skal være fikset i 0.77. Se https://github.com/agensdev/darjeeling/blob/main/app/src/androidTest/java/no/agens/darjeeling/EventuallyActivityLaunchedTest.kt for eksempel på bruk.
